Logging:
  Elastic.Apm: "Warning"
ElasticApm:
  ServiceName: Report.Service
  ServerUrl: http://apm-server:8200
  Environment: production
  CaptureBody: all
  TransactionSampleRate: 1.0
Logstash:
  Uri: http://logstash:28080
  ServiceName: Report.Service
  Environment: production
OtelCollector:
  Endpoint: http://jaeger:4317
  ServiceName: Report.Service
URLServices:
  Pricing: http://pricing.service:8080/api/pricing
ConnectionStrings:
  PoliciesConnection: Server=mysql;Port=3306;Database=Microservices.Demo.Policies;User=root;Password=Password1234
Kafka:
  BootstrapServers: kafka:9092
  Producers:
    Events:
      GroupId: policy.events.producer.group
      Topics:
      - Policy: policy.events
Persistence:
  Outbox:
    MessagingConnection: Server=sqlserver,1433;Database=Microservices.Demo.MessagesBox;User Id=sa;Password=Password1234;TrustServerCertificate=True;Encrypt=False;
    TableName: OutboxMessagesPolicies
